networks:
  inception:
    driver: "bridge"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/http.d/
      - wp-volume:/var/www/
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306"
    volumes:
    - db-volume:/var/lib/mysql

volumes:
  wp-data:
  db-data: