networks:
  inception:
    driver: "bridge"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception

volumes:
  wp-volume:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/inception/wp
  db-volume:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/inception/db